In [12]:
import numpy as np

def stable_softmax(x: np.ndarray, axis: int = -1) -> np.ndarray:
    """
    Computes numerical stable softmax along the specified axis.
    
    Formula: exp(x_i - max(x)) / sum(exp(x_j - max(x)))
    """
    max_x = np.max(x, axis=axis, keepdims=True)
    print(max_x)
    print(x - max_x) # max_x broadcast to fit same size as x

    exp_x = np.exp(x - max_x)
    print(exp_x)
    print(np.sum(exp_x, axis=axis, keepdims=True)) # sum broadcast to fit same size as exp_x

    return exp_x / np.sum(exp_x, axis=axis, keepdims=True)

In [ ]:
arr1 = np.array([[1, 2, 3, 4], [5, 16, 7, 28]]) # 2D array
print(stable_softmax(arr1))

[[ 4]
 [28]]
[[ -3  -2  -1   0]
 [-23 -12 -21   0]]
[[4.97870684e-02 1.35335283e-01 3.67879441e-01 1.00000000e+00]
 [1.02618796e-10 6.14421235e-06 7.58256043e-10 1.00000000e+00]]
[[1.55300179]
 [1.00000615]]
[[3.20586033e-02 8.71443187e-02 2.36882818e-01 6.43914260e-01]
 [1.02618166e-10 6.14417460e-06 7.58251383e-10 9.99993855e-01]]


In [ ]:
arr2 = np.array([
    [[1, 2, 3, 4],
     [5, 16, 7, 28]],
    [[2, 4, 6, 8],
     [3, 4, 2, 9]]]) # 3D array
print(stable_softmax(arr2))

[[[ 4]
  [28]]

 [[ 8]
  [ 9]]]
[[[ -3  -2  -1   0]
  [-23 -12 -21   0]]

 [[ -6  -4  -2   0]
  [ -6  -5  -7   0]]]
[[[4.97870684e-02 1.35335283e-01 3.67879441e-01 1.00000000e+00]
  [1.02618796e-10 6.14421235e-06 7.58256043e-10 1.00000000e+00]]

 [[2.47875218e-03 1.83156389e-02 1.35335283e-01 1.00000000e+00]
  [2.47875218e-03 6.73794700e-03 9.11881966e-04 1.00000000e+00]]]
[[[1.55300179]
  [1.00000615]]

 [[1.15612967]
  [1.01012858]]]
[[[3.20586033e-02 8.71443187e-02 2.36882818e-01 6.43914260e-01]
  [1.02618166e-10 6.14417460e-06 7.58251383e-10 9.99993855e-01]]

 [[2.14400878e-03 1.58422012e-02 1.17058913e-01 8.64954877e-01]
  [2.45389767e-03 6.67038546e-03 9.02738505e-04 9.89972978e-01]]]


In [17]:
print(arr2 / 5) # broadcasting

[[[0.2 0.4 0.6 0.8]
  [1.  3.2 1.4 5.6]]

 [[0.4 0.8 1.2 1.6]
  [0.6 0.8 0.4 1.8]]]


In [25]:
mask = np.array([
    [False, False, False],
    [False, False, False]
])

print(mask)
if mask is not None:
    print("hello")

[[False False False]
 [False False False]]
hello


In [29]:
mask = [[]]

print(mask)
if mask:
    print("hello")

[[]]
hello
